### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by jaanos** [vitorozman/APPR-2020-21#1]
Vidim, da imaš trenutno razpredelnico za vsako leto. Ker imaš povsod enake stolpce (razen za leto 2020), lahko te razpredelnice združiš v eno, pri tem pa bistveno skrajšaš kodo, saj se ta večkrat ponovi, npr.:
```R
leta <- 15:19 # leta, za katere obdelujemo podatke
Tabela <- lapply(leta, function(leto)
                 sprintf("podatki/billionaires%d.json", leto) %>% # sestavimo ime datoteke
                   fromJSON(file=.) %>%
                   .$personList %>% .$personsLists %>%
                   lapply(. %>% .[stolpci_json] %>% setNames(stolpci_new) %>%
                            lapply(. %>% { ifelse(is.null(.), NA, .) }) %>%
                            as.data.frame()) %>% bind_rows() %>% .[1:200, ] %>%
                   mutate(Leto=2000+leto)) %>% bind_rows() %>%
  rbind(Tabela20 %>% transmute(ImePriimek, Premozenje, Vir, Leto=2020)) # dodani še ustrezni stolpci za 2020
```

Iz podatkov za leto 2020 izpelješ še štiri razpredelnice, kjer izbiraš različne stolpce. Po tem ne vidim potrebe - če boš potreboval te podatke pri vizualizaciji, lahko vedno uporabiš razpredelnico za 2020 in ustrezno uporabiš želene stolpce.

**Comment by vitorozman** [comment]
Kodo sem preuredil. Hvala za popravek.
