### ISSUE TITLE
Error pri zagon z binderjem

### ISSUE THREAD

**Issue by vitorozman** [vitorozman/APPR-2020-21#2]
Imam težavo pri zagonu projekta z binderjem. Ko projekt poženem mi binder prebavi potem pa ko hoče prikazati poročilo dobim error in ne piše konkretnega razloga. Če projekt poženem v RStudiu, mi zadevo brez težav prikaže.

**Comment by vitorozman** [comment]
Opazil sem da se težava pojavi pri zagonu skripte _analiza.r_
Problem dela _loess_
```
#tabela top_1 vsebuje stopce (ImePriimek=najbogatejsi, Leto=2016-2020, Rast)
prileganje <- loess(formula = (Rast ~ Leto), data=top_1) # imel sem tudi varjanto: glm(formula = (Rast ~ Leto), data=top_1)
leta <- data.frame(Leto=seq(2016, 2021, 1))
napoved <- mutate(leta, Rast=predict(prileganje, leta))
top_1 <- top_1 %>% rbind(napoved %>% filter(Leto==2021))

# NA vrednosti zamenjam s konkretnimi vrednostmi tj. prihodnje premozenje in ImePriimek
top_1$ImePriimek[is.na(top_1$ImePriimek)] <- top_1$ImePriimek[1]
top_1$Premozenje[is.na(top_1$Premozenje)] <- round((top_1$Premozenje[length(top_1$Premozenje)-1]) * (1 + top_1$Rast[length(top_1$Rast)]/100))

# izris grafa
ggTop_napoved <- ggplot(data=top_1, aes(x=Leto, y=Rast)) +
  geom_point(na.rm = TRUE) +
  geom_smooth(method="loess", formula =  y ~ x) 
```

Graf se čisto lepo izriše, vedar pa dobim polno opozoril že ko poženem `prileganje <- loess(formula = (Rast ~ Leto), data=top_1)`:

_Warning messages:
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  Chernobyl! trL>n 6
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  Chernobyl! trL>n 6
3: In sqrt(sum.squares/one.delta) : NaNs produced
4: In stats::qt(level/2 + 0.5, pred$df) : NaNs produced
5: In max(ids, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf_

**Comment by jaanos** [comment]
Očitno je podatkov premalo, da bi bilo smiselno uporabiti `loess` - opaziš lahko, da gre krivulja skozi vse točke. Sicer pa `loess` ni mogoče uporabiti za napovedovanje izven intervala s podatki, tako da je bolje, da uporabiš kakšen drugačen model (glede na podatke bi bil morda smiseln kvadraten model). Vsekakor pa uporabi isti model za napovedovanje in prikaz krivulje na grafu.

Sicer pa do težave pride pri uporabi `rbind` v `analiza.r`, saj združuješ razpredelnice z različnim številom stolpcev. Svetujem, da narediš nekaj takega:
```R
top_1 <- top %>% filter(ImePriimek == "Jeff Bezos") %>%
  ungroup %>% select(-Vir, -ImePriimek)

prileganje <- glm(data=top_1, Rast ~ Leto) # morda raje kvadratni model - glej zgoraj
leta <- data.frame(Leto=seq(2016, 2021, 1))
napoved <- leta %>% mutate(Rast=predict(prileganje, leta),
                           Premozenje=c(NA, top_1$Premozenje) * (1+Rast/100))

ggTop_napoved <- ggplot(data=napoved %>% filter(Leto == 2021) %>% rbind(top_1),
                        aes(x=Leto, y=Rast)) +
  geom_point(aes(color=(Leto == 2021)), na.rm=TRUE) +
  geom_text(aes(label=ifelse(Leto == 2021, round(Premozenje, -3), "")), nudge_y=5) + # napoved rasti in premoženja
  labs(y="Rast (%)") +
  geom_smooth(data=top_1, method="glm", formula=y ~ x, fullrange=TRUE) +
  ylab("Rast premoženja v %") +
  labs(title="Napoved rasti premoženja za leto 2021 - Jeff Bezos") +
  theme(axis.ticks=element_line(color="red"), 
        axis.ticks.length=unit(2, "mm"),
        legend.position="none")
```
Bi opozoril še na to, da se podatke zaokrožuje samo za potrebe izpisa, in ne, ko se bo z njimi še računalo ali jih izrisovalo (to je zgoraj upoštevano).

**Comment by vitorozman** [comment]
Hvala za popravek. Binder mi sedaj dela.
