### ISSUE TITLE
Zakjuček projekta

### ISSUE THREAD

**Issue by vitorozman** [vitorozman/APPR-2020-21#3]
Pozdravljeni,
mislim da sem projekt zaključil in bi prosil za pregled pred odobritvijo.
Hvala

**Comment by jaanos** [comment]
Poročilo deluje, tako da bom dodal povezavo do projekta na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Imam samo nekaj pripomb estetske narave:
* Če bi na grafu povprečnega premoženja po starosti želel stolpce pobarvati (namesto, da jih samo obrobiš), lahko namesto parametra `color` uporabiš parameter `fill`.
* Svetoval bi, da oznake na zemljevidu nekoliko zmanjšaš (morda celo prilagodiš velikosti države) Poskrbi tudi, da bo naslov legende lepo berljiv (presledek, šumniki).
* Pri aplikaciji Shiny v poročilu povečaj parameter `height`, da se znebiš drsnika.

**Comment by vitorozman** [comment]
Sedej sem popravil prvo in tretjo točko, pri drugi pa sem se malo zataknil. Ne znam prilagoditi velikosti črk na zemljevidu, če jih zmanjšam so premajhne, tudi ko povečujemo države.  
Legendo pa sem dopolnil.

**Comment by jaanos** [comment]
Sem posodobil povezavo.

Sem tudi sam poskusil nekoliko prilagoditi pisavo na zemljevidu, pa nisem našel boljšega načina - bo kar v redu tako, kot je.
